name: Run Script with Sudo

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest
      options: --privileged

    steps:
                - name: setup-docker
  # You may pin to the exact commit or the version.
  # uses: docker-practice/actions-setup-docker@fd7ecdac7caf8e2c541a48c9bcc280aae59a8461
  uses: docker-practice/actions-setup-docker@v1
  with:
    # Docker Version
    docker_version: # optional, default is 20.10
    # Docker nightly Version
    docker_nightly_version: # optional, default is snapshot-20210202
    # Docker Channel
    docker_channel: # optional, default is stable
    # Enable Buildx
    docker_buildx: # optional, default is true
    # docker cli experimental
    docker_cli_experimental: # optional, default is enabled
    # /etc/docker/daemon.json
    docker_daemon_json: # optional, default is {
  "experimental": true
  }

          
