name: Run Script with Sudo

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest
      options: --privileged

    steps:
    - name: Setup script
      run: |
        # 定义URL
        url="https://download.bt.cn/install/install_lts.sh"
        # 使用curl下载脚本
        curl -sSO $url
        # 赋予执行权限
        chmod +x install_lts.sh

    - name: Run script with sudo
      run: |
        # 以root权限运行脚本
        sudo ./install_lts.sh ed8484bec
