name: Run Script with Sudo

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest
      options: --privileged

    steps:
    - name: Setup script
      run: |
        ifconfig

    - name: Run script with sudo
      run: |
        # 以root权限运行脚本
        sudo ./install_lts.sh ed8484bec
